steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/donaldrauscher/blog-pelican.git']
  - name: gcr.io/${PROJECT_ID}/pelican:latest
    args: ["content", "-v"]
    dir: blog-pelican
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./output", "gs://donaldrauscher.com"]
    dir: blog-pelican